### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by signalpoint** [alexschedrov/DrupalGapManager#1]
I'm not quite sure where I should clone this project. So I cloned it into my localhost mobile application directory, for example:

```
/var/www/drupal-7/mobile-application/DrupalGapManager
```

Is this correct? If so, how do I "run" it?

If not, where should it live, and how do I "run" it?

Thanks!

**Comment by alexschedrov** [comment]
Hi @signalpoint,

I have updated README.md, there you can find instructions how to install it and commands which currently available. See https://github.com/Sanchiz/DrupalGapManager page.

Currently it's only "create" command. I will send you an email about modules(dl, en, dis commands).

Thanks!

**Comment by signalpoint** [comment]
@Sanchiz excellent, thank you. I am going to make a companion module (that will only need to be installed on drupalgap.org) that will have service resources for the `download` and `update` features, so we can easily get project download details, and update details.
