### ISSUE TITLE
Cordova Plugins Not Installed

### ISSUE THREAD

**Issue by signalpoint** [alexschedrov/DrupalGapManager#16]
I just ran this command:

```
dgm create android Example --url=http://www.example.com
```

Then running this:

```
cordova plugin list
```

Revealed that no plugins were installed, so I manually had to run this:

```
cordova plugin add org.apache.cordova.console org.apache.cordova.device org.apache.cordova.dialogs org.apache.cordova.file org.apache.cordova.inappbrowser org.apache.cordova.network-information
```

I thought I recalled not having to do this step, so just an FYI...

**Comment by alexschedrov** [comment]
@signalpoint, thanks! I will check. I can't reproduce on my machine.

**Comment by signalpoint** [comment]
@Sanchiz thank you for the follow up, I believe I should totally uninstall my entire Android environment and start from scratch, it is behaving quite strangely.
