### ISSUE TITLE
How to Implement Improvements

### ISSUE THREAD

**Issue by signalpoint** [alexschedrov/DrupalGapManager#2]
Disclaimer: This is my first experience "developing" with node...

If I am understanding this correctly, I am able to clone my fork of this repository, and from inside that directory I can use this command to execute my local copy of DGM:

```
node bin/dgm.js
```

This is contrary to running the following terminal command, which runs the version of DGM that was installed via `npm install dgm`

```
dgm
```

At first, while running `node bin/dgm.js`, I received the following error:

```
Error: Cannot find module 'cordova'
```

I was able to resolve it by running this:

```
sudo npm link cordova
```

Subsequently I received the following errors, one by one:

```
Error: Cannot find module 'fs-extra'
Error: Cannot find module 'validator'
Error: Cannot find module 'underscore'
Error: Cannot find module 'request'
Cannot find module 'minimist'
```

I was able to resolve these errors with the following terminal commands:

```
sudo npm link fs-extra
sudo npm link validator
sudo npm link underscore
sudo npm link request
sudo npm link minimist
```

Will you please elaborate on these findings so I may better understand a DGM development environment? Thanks!

**Comment by alexschedrov** [comment]
Hi @signalpoint,

There are 2 ways how you can use nodeJS application:
- Globally
- Locally(you can use it only from folder)

If you will use it locally, firstly you need install dependencies, run `npm install -d` from folder where exist package.json.

I have added wiki page where explains uses of DGM applications. How use can use it and how you can work on the code from GitHub.

https://github.com/Sanchiz/DrupalGapManager/wiki/Development-guide
