### ISSUE TITLE
Understanding the App's Context

### ISSUE THREAD

**Issue by signalpoint** [alexschedrov/DrupalGapManager#3]
Are we going to be able to load the settings.js file into the dgm context? For example, I'd like to work on the `pml` command to print out the list of modules within the app, and then see if they are enabled or not.

Unfortunately the settings.js file is implemented in a way that it expects the `drupalgap` JSON object to already be instantiated. Do we perhaps want to move away from a settings.js file and into a settings.yaml file (or other)? Or can we fake a `drupalgap = {};` from withint the `dgm` environment behind the scenes?

**Comment by alexschedrov** [comment]
I've added new module "lib/drupalgap.js" and now we can use settings.js and DrupalGap context. How to use:

```
var drupalgap = require('../drupalgap');

drupalgap.init(function(drupalgapContext) {
  // In drupalgapContext we have all data from settings.js.
});
```

I think moving of module configurations to the settings.yaml or other that's good idea. It allows easier work with modules (en, dis and etc.), but it's not so urgent. Good idea for a future feature.
