### ISSUE TITLE
Updating DGM

### ISSUE THREAD

**Issue by signalpoint** [alexschedrov/DrupalGapManager#4]
If I were a regular user (i.e. not using a git clone of DGM), how do I update to the latest release of DGM available from nodejs? What nodejs command(s) should be used and from what directory(ies)? Thanks!

**Comment by alexschedrov** [comment]
You can update DGM with command:

```
npm update -g dgm
```

or

```
sudo npm update -g dgm
```

To check available updates: 

```
npm outdated
```
