### ISSUE TITLE
dgm create web mobile-application

### ISSUE THREAD

**Issue by signalpoint** [alexschedrov/DrupalGapManager#6]
Creates the mobile-application directory inside the Drupal root folder, downloads and extracts the sdk, etc. Essentially the same as the android/ios commands, but skips all the PhoneGap/Cordova stuff. I now see that this command would be related to your proposed "dgm dl" command which just downloads the SDK.

**Comment by alexschedrov** [comment]
Done.

Now we can download only SDK with command:

```
dgm create web <PATH> [--url=SITE_URL]
```

Available in dev version.
