### ISSUE TITLE
Theme Skeleton

### ISSUE THREAD

**Issue by signalpoint** [alexschedrov/DrupalGapManager#9]
It'd be cool to be able to automatically create a theme and a bunch of default stuff. For example:

```
dgm create theme my_theme
```

And it would essentially create the new directory and add all these files with their content:

http://www.drupalgap.org/node/121

**Comment by alexschedrov** [comment]
Done.

Now we can create new theme via command:

```
dgm create-theme <NAME>
dgm create-theme awesome_theme
```
